version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure:10
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: library/mysql:8.0.25
    restart: always
    environment:
#            - MYSQL_ROOT_PASSWORD=123456
#            - MYSQL_PASSWORD=123456
#            - MYSQL_DATABASE=quiz
      MYSQL_USER: test            #ユーザアカウント
      MYSQL_PASSWORD: 123456    #ユーザアカウントのパスワード
      MYSQL_DATABASE: testDb
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306